### ISSUE TITLE
New release? ;-)

### ISSUE THREAD

**Issue by gbastien** [4teamwork/ftw.labels#54]
That is not really an issue though, but it would be great!

Thank you,

Gauthier

**Comment by njohner** [comment]
Hi @gbastien,
It seems we did not realise your last commit (https://github.com/4teamwork/ftw.labels/commit/c0baa972548b00bf1453fce1f4a20af5dcef96bc)
breaks our tests.

Changing the `LabelsJar._redirect` to the referer will send you back to the `edit_label` view when you submit the form from the `edit_label` view. But this view needs a `label_id` to be set in the request.
I'm not too sure it even makes sense to be sent back to the edit view? What is it you wanted to do here and why?

Thanks,

Niklaus

PS: You can run the tests simply with `bin/test` after building the package.

**Comment by gbastien** [comment]
Hi @njohner 

the edit form is displayed in the portlet.  We have a usecase where the portlet is displayed on a place where we have htttp://.../my_page?fieldset=data as url, so redirecting to http_referer will keep "?fieldset=data" 

Maybe when the view is called directly (but is that an existing possibility?) then the referer is not correct.

I do not know if the case of calling the view without a correct http_referer is relevant.  Maybe we may fix the http_referer in the tests?

What do you think?

Gauthier

**Comment by gbastien** [comment]
@njohner 

just to add that, when used thru the portlet to create/update/remove a label, everything works as expected...  So I think we should set the http_referer in the tests...

Gauthier

**Comment by gbastien** [comment]
Hi @jone @njohner 

sorry to come back with that, what do you think about this issue?  Either we revert the change and I may manage it in an override, or we could adapt test as long as this view is only used thru the portlet, I do not really know?

Thank you,

Gauthier

**Comment by jone** [comment]
Hey @gbastien, sorry for waiting.

Your referer pull request actually broke the tests and had a bug. We didn't notice since our CI is set up to not test PRs of forks and I merged too early (we are not merging when the tests don't pass).
I have refactored the redirecting strategy in #56 and fixed the tests.

I have now cut a release `ftw.labels = 1.2.0` with your changes.

Cheers

**Comment by gbastien** [comment]
Hi @jone 

thank you for the fix and the new release, sorry for the delay!

Gauthier
