### ISSUE TITLE
In production mode the cross icon to remove a selected label is not shown

### ISSUE THREAD

**Issue by gbastien** [4teamwork/ftw.labels#55]
Hi,

I noticed that the cross in the select2 input showing selected elements is not shown when using production/CSS compiled mode, do you confirm?  So just disabling "Development mode" in portal_css will do "remove label cross icon" not appear.

Do you confirm?  If so I propose a PR, actually it is just necessary to check the "Replace relative paths in url() statements with absolute paths?" box of "++resource++ftw.labels/select2.css" in portal_css.

Thank you,

Gauthier

**Comment by gbastien** [comment]
Hi @jone 

see #57 

Thank you,

Gauthier

**Comment by jone** [comment]
@gbastien thanks! Your fix is in `ftw.labels = 1.2.1`.

**Comment by gbastien** [comment]
@jone great thank you!

Gauthier
