### ISSUE TITLE
label by user

### ISSUE THREAD

**Issue by sgeulette** [4teamwork/ftw.labels#58]
Hi,
we are currently using your product. It's fine.
We have now demands to store labels by user. 
By example, each user could select label 'read', 'to follow', etc.
It could be a new boolean label field, 'by user'.
Index could contains too: 'user1:label1', 'user2: label1'. 

What do you thing about this new feature ?
Could it be integrated in the same product ? If not, we will do another product extending yours.

Regards

**Comment by sgeulette** [comment]
Hi,
I have implemented those functionality in a [fork](https://github.com/sgeulette/ftw.labels)
You can test it if you want. 

An improvement would be to add a different permission than "ftw.labels: Change Labels" to set personal labels ("ftw.labels: Change Personal Labels") and list and set labels following given permission

Regards

**Comment by jone** [comment]
Hi Stéphan

Thank you for interest in this product and your will to contribute!
I've taken a glance at your branch, it looks promising.
We will happily accept this enhancement if you have time to make a pull request!

Thanks and cheers
Jonas

**Comment by sgeulette** [comment]
Hi Jonas,

thanks for your reply.
I think it would be more interesting to use 2 different permissions for each label type. 
I will do this modification and adapt the readme before the pull request. 

Regards
Stephan
